
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Sep 14 00:30:34 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 53;
  public static final int CONST = 6;
  public static final int GE = 29;
  public static final int CASE = 45;
  public static final int LPAREN = 14;
  public static final int SEMI = 7;
  public static final int CONTINUE = 24;
  public static final int FILTER = 44;
  public static final int FOR = 46;
  public static final int MINUS = 32;
  public static final int CHARACTER = 58;
  public static final int RPAREN = 15;
  public static final int AND = 37;
  public static final int LT = 28;
  public static final int OR = 38;
  public static final int BOOL = 57;
  public static final int COMMA = 8;
  public static final int CLASS = 48;
  public static final int INC = 16;
  public static final int DIV = 34;
  public static final int PLUS = 31;
  public static final int IF = 41;
  public static final int ASSIGN = 5;
  public static final int DOT = 18;
  public static final int LE = 27;
  public static final int FINDANY = 52;
  public static final int ABSTRACT = 50;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int NEW = 36;
  public static final int error = 1;
  public static final int MUL = 33;
  public static final int NUMBER = 56;
  public static final int MOD = 35;
  public static final int NEQ = 26;
  public static final int IDENT = 55;
  public static final int BREAK = 20;
  public static final int VOID = 13;
  public static final int EQ = 25;
  public static final int SWITCH = 43;
  public static final int LBRACK = 9;
  public static final int ARROW = 54;
  public static final int COLON = 40;
  public static final int ELSE = 42;
  public static final int LBRACE = 2;
  public static final int ENUM = 47;
  public static final int READ = 21;
  public static final int RBRACK = 10;
  public static final int WHILE = 11;
  public static final int RBRACE = 3;
  public static final int EXTENDS = 49;
  public static final int PROG = 4;
  public static final int QUESTION = 39;
  public static final int DEC = 17;
  public static final int SWAP = 51;
  public static final int GT = 30;
  public static final int PRINT = 23;
  public static final int LENGTH = 19;
  public static final int DO = 12;
}

