
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Sep 01 01:11:01 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 49;
  public static final int CONST = 6;
  public static final int GE = 27;
  public static final int CASE = 42;
  public static final int LPAREN = 12;
  public static final int SEMI = 7;
  public static final int CONTINUE = 22;
  public static final int FOR = 43;
  public static final int MINUS = 30;
  public static final int CHARACTER = 54;
  public static final int RPAREN = 13;
  public static final int AND = 35;
  public static final int LT = 26;
  public static final int OR = 36;
  public static final int BOOL = 53;
  public static final int COMMA = 8;
  public static final int CLASS = 45;
  public static final int INC = 14;
  public static final int DIV = 32;
  public static final int PLUS = 29;
  public static final int IF = 39;
  public static final int ASSIGN = 5;
  public static final int DOT = 16;
  public static final int LE = 25;
  public static final int FINDANY = 48;
  public static final int ABSTRACT = 47;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int MUL = 31;
  public static final int NUMBER = 52;
  public static final int MOD = 33;
  public static final int NEQ = 24;
  public static final int IDENT = 51;
  public static final int BREAK = 18;
  public static final int VOID = 11;
  public static final int EQ = 23;
  public static final int SWITCH = 41;
  public static final int LBRACK = 9;
  public static final int ARROW = 50;
  public static final int COLON = 38;
  public static final int ELSE = 40;
  public static final int LBRACE = 2;
  public static final int ENUM = 44;
  public static final int READ = 19;
  public static final int RBRACK = 10;
  public static final int RBRACE = 3;
  public static final int EXTENDS = 46;
  public static final int PROG = 4;
  public static final int QUESTION = 37;
  public static final int DEC = 15;
  public static final int GT = 28;
  public static final int PRINT = 21;
  public static final int LENGTH = 17;
}

